#!/usr/bin/bash
backend_command() { cd backend && poetry run python manage.py "$@"; }
run_frontend_command() { 
    cd frontend;
    npm run dev &
    wait;
}
run_server() { 
    backend_command runserver &
    run_frontend_command;
    wait; 
}
lint_format_command() {
    cd backend; \
    poetry run black .; \
    cd ../frontend; \
    npm run lint;
    npx prettier --write .;
}

get_command() {
    echo "Budget App Server Commands"
    echo "========================"
    echo "1. Run app"
    echo "2. Run backend"
    echo "3. Run frontend"
    echo "4. Run backend shell"
    echo "5. Run Lint and format"


    read -p "Enter choice: " choice
    case $choice in
    1)
        run_server
        exit
        ;;
    2)
        echo "Starting Backend"
        backend_command runserver
        exit
        ;;
    3)
        echo "Starting Frontend"
        run_frontend_command
        exit
        ;;
    4)
        echo "Running Python Shell"
        backend_command shell
        exit
        ;;
    5)
        echo "Linting and Formatting"
        lint_format_command
        exit
        ;;
    *)
        echo "Invalid Choice"
        exit
        ;;
    esac
}

case $1 in
    "run")
        run_server
        ;;
    "backend")
        backend_command runserver
        ;;
    "frontend")
        run_frontend_command
        ;;
    "shell")
        backend_command shell
        ;;
    "lint")
        lint_format_command
        ;;
    *)
        get_command
        ;;
esac
