# Generated by Django 4.0.6 on 2022-07-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='_user',
        ),
    ]
