# Generated by Django 4.0.6 on 2022-07-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_account__user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='_user',
            new_name='user',
        ),
    ]
